# Generated by Django 4.1.3 on 2022-12-05 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MiAppFamilia', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hobby',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hobbypadre', models.CharField(max_length=40)),
                ('hobbymadre', models.CharField(max_length=40)),
            ],
        ),
    ]
