# Generated by Django 4.1.3 on 2022-12-05 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MiAppFamilia', '0002_hobby'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Hobby',
        ),
    ]
